"""add_performance_indexes

Revision ID: d0461836e947
Revises: 2d325e5a846f
Create Date: 2026-04-30 12:33:22.395670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0461836e947'
down_revision: Union[str, Sequence[str], None] = '2d325e5a846f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_attendance_date', 'attendance', ['attendance_date'], unique=False)
    op.create_index('idx_attendance_e_id', 'attendance', ['e_id'], unique=False)
    op.create_index('idx_courses_t_id', 'courses', ['t_id'], unique=False)
    op.create_index('idx_courses_title', 'courses', ['title'], unique=False)
    op.create_index('idx_enrollments_c_id', 'enrollments', ['c_id'], unique=False)
    op.create_index('idx_enrollments_s_id', 'enrollments', ['s_id'], unique=False)
    op.alter_column('examination', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'upcoming'::character varying"))
    op.create_index('idx_examination_c_id', 'examination', ['c_id'], unique=False)
    op.create_index('idx_exams_students_ex_id', 'exams_students', ['ex_id'], unique=False)
    op.create_index('idx_exams_students_s_id', 'exams_students', ['s_id'], unique=False)
    op.create_index('idx_fees_s_id', 'fees', ['s_id'], unique=False)
    op.create_index('idx_fees_status', 'fees', ['status'], unique=False)
    op.create_index('idx_students_class_section', 'students', ['class_name', 'section'], unique=False)
    op.create_index('idx_students_name', 'students', ['name'], unique=False)
    op.create_index('idx_teachers_name', 'teachers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_teachers_name', table_name='teachers')
    op.drop_index('idx_students_name', table_name='students')
    op.drop_index('idx_students_class_section', table_name='students')
    op.drop_index('idx_fees_status', table_name='fees')
    op.drop_index('idx_fees_s_id', table_name='fees')
    op.drop_index('idx_exams_students_s_id', table_name='exams_students')
    op.drop_index('idx_exams_students_ex_id', table_name='exams_students')
    op.drop_index('idx_examination_c_id', table_name='examination')
    op.alter_column('examination', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'upcoming'::character varying"))
    op.drop_index('idx_enrollments_s_id', table_name='enrollments')
    op.drop_index('idx_enrollments_c_id', table_name='enrollments')
    op.drop_index('idx_courses_title', table_name='courses')
    op.drop_index('idx_courses_t_id', table_name='courses')
    op.drop_index('idx_attendance_e_id', table_name='attendance')
    op.drop_index('idx_attendance_date', table_name='attendance')
    # ### end Alembic commands ###
